README.md, provers-containerised/README.md, starexec-containerised/README.md, starexec-kubernetes/README.md, starexec-proxy-provers/README.md, starexec-tptp/ServiceTools/README.md
Enhance the README to improve clarity and consistency across various sections, including containerization, build and run instructions, deployment with MicroK8s and Terraform on EKS, proxy-prover creation, and ServiceTools description.
=> Refine README for clarity and structure improvements

.gitignore, starexec-containerised/.dockerignore, starexec-containerised/Dockerfile, starexec-containerised/Makefile, starexec-containerised/init-starexec.sh
Add environment variable checks, improve SSH key setup, and transition to a Debian base image.Enhance container permissions and startup processes for better maintainability and clarity.
=> Enhance container setup and environment management

starexec-containerised/Dockerfile, starexec-containerised/Jenkinsfile, starexec-containerised/Makefile, starexec-containerised/dockerPackage/allScripts/osScripts/SetupUsers.sh, starexec-containerised/dockerPackage/allScripts/starexecScripts/HttpdConfigAndRun.sh
Implement a Jenkins pipeline for automated Podman builds, and refactor the SSH key setup in the Makefile for improved clarity and efficiency.
=> Add Jenkins pipeline and refactor SSH setup

starexec-containerised/Dockerfile
Change the exposed port from 80 to 8080 in the Dockerfile to accommodate application requirements.
=> Update Dockerfile to expose port 8080

starexec-containerised/Makefile
Enhance the container cleanup process by safely checking and removing images, handling dangling image cleanup, and prompting for confirmation before resetting Podman.
=> Refactor container cleanup process for Podman

provers-containerised/Makefile, provers-containerised/provers/Dockerfile, provers-containerised/provers/E---3.0.03/Dockerfile, provers-containerised/provers/E---3.2.5/Dockerfile, provers-containerised/provers/Leo-III---1.7.0/Dockerfile, provers-containerised/provers/Vampire---4.9/Dockerfile, provers-containerised/run_image.py, provers-containerised/tptp-world/Dockerfile, provers-containerised/ubuntu-arc/Dockerfile
Enhance the Dockerfile by streamlining package installation, optimizing build steps, and improving artifact handling. Clean up the Makefile by removing unnecessary blank lines for better readability. Rename helper functions for clarity and extract main logic into dedicated functions.
=> Refactor Dockerfile and Makefile for improved readability and efficiency

.github/workflows/starexec-containerised.yaml, .github/workflows/starexec-containerized-makefile-build.yaml
Introduce a GitHub Actions workflow to automate the building and publishing of Docker images for the StarExec container, enhancing the CI/CD process. Refactor existing workflow for improved efficiency.
=> Add GitHub Actions workflow for building StarExec container

starexec-containerised/init-starexec.sh
Refactor the database initialization process for consistent SQL changes and implement background monitoring for critical services to minimize downtime.
=> Refactor database setup and add service monitoring

starexec-containerised/Makefile, starexec-containerised/init-starexec.sh
Reduces sleep delay for faster Tomcat shutdown and updates Tomcat options to support multiple versions.
Adds MySQL data directory initialization with a timeout loop for reliable startup.
=> Refines container init script execution

starexec-containerised/Dockerfile
Include vim in the Dockerfile to improve text editing options within the container.
=> Add vim to Dockerfile for enhanced text editing capabilities

starexec-containerised/README.md
Enhance the README by adding detailed instructions for creating certificates and improving overall formatting for better readability.
=> Update README with certificate creation instructions and formatting improvements

starexec-kubernetes/microk8s/Makefile, starexec-kubernetes/microk8s/README.md, starexec-kubernetes/microk8s/YAMLFiles/deployment.yaml, starexec-kubernetes/microk8s/YAMLFiles/headnode-role-binding.yaml, starexec-kubernetes/microk8s/YAMLFiles/ingress.yaml, starexec-kubernetes/microk8s/YAMLFiles/service.yaml
Improve TLS certificate handling and deployment processes for StarExec, including resource limits and better identification through labels. Update documentation to reflect changes in deployment instructions and Makefile targets. #14
=> Enhance TLS management and deployment configuration

starexec-kubernetes/terraform/README.md
Improve clarity and readability of the README by reorganizing prerequisites and setup steps, standardizing bullet points, headings, and spacing.
=> Update README formatting for Terraform deployment

starexec-kubernetes/run_image_k8s.py
Standardize code style, improve readability, and clean up formatting in the k8s job runner script.
=> Reformat k8s job runner code for readability

.github/workflows/starexec-kubernetes.yaml
Reorganize CI workflow by renaming and restructuring validation jobs for Terraform and Kubernetes. Enhance Terraform validation with detailed format diff output and conditional error reporting. Streamline Kubernetes manifest checks into a single command for multiple directories.
=> Refine Terraform and Kubernetes validation workflows

starexec-kubernetes/terraform/main.tf
Standardize whitespace and alignment in Terraform configuration to enhance code readability and maintainability.
=> Reformat Terraform code for consistency

starexec-proxy-provers/helpers.py, starexec-proxy-provers/make_proxy.py
Enhance readability and maintainability by improving code formatting and adding comments in the image handling functions and the make_proxy.py script.
=> Improve code formatting and comments in image handling and proxy creation scripts

provers-containerised/run_image.py
Enhance the clarity and structure of argument handling and formatting in the run_image.py script, improving maintainability and readability.
=> Refactor argument handling and formatting in run_image.py

requirements.txt, starexec_automation.py
Introduce an automated script that facilitates login, solver and benchmark uploads, and job creation through the StarExec web interface, along with enhanced error handling, logging, and CLI argument support.
=> Add Selenium automation for StarExec

starexec-containerised/Makefile, starexec-containerised/README.md, starexec-containerised/init-starexec.sh
Introduce a healthcheck function to monitor the status of MySQL, Apache, Tomcat, and the application. Improve database initialization by conditionally creating the database and integrating SQL reload/update. Enhance Podman container management with state backup/restore, improved logging, and support for MicroK8s. Update documentation to clarify persistent run and state management instructions.
Related issue #26
=> Add service healthcheck and enhance Podman lifecycle management

.gitignore
Include Visual Studio Code settings and backup files in the .gitignore to prevent them from being tracked in the repository.
=> Update .gitignore for Visual Studio Code and backup files

starexec-kubernetes/microk8s/Makefile, starexec-kubernetes/microk8s/README.md
Introduce state backup/restore, health checks, and improved TLS/SSH key management to enhance deployment consistency and lifecycle commands.
Related issue #26
=> Enhance deployment lifecycle management for MicroK8s

starexec_automation.py
Reformat code by removing unused imports, adjusting whitespace, and updating quotes to enhance clarity and maintainability without altering functionality.
=> Standardize code formatting and improve readability

starexec-containerised/dockerPackage/configFiles/ssl.conf, starexec-containerised/dockerPackage/configFiles/starexec.conf, starexec-kubernetes/microk8s/YAMLFiles/ingress.yaml
Refine SSL settings and manage forwarded headers more effectively. Remove unused HTTP proxy directives and ensure SSL redirection is enabled for ingress. Adjustments improve security and maintain proper header forwarding.
=> Update SSL and proxy header configurations

starexec-kubernetes/microk8s/Makefile, starexec-kubernetes/microk8s/README.md
Implement dynamic detection of the SSH username with fallback logic, separate the application of manifests from ConfigMap creation, and enhance the cleanup process with forced deletion and resource labeling.
=> Dynamic SSH user detection and refined deployment process

starexec-containerised/Makefile
Introduce an interactive prompt for selecting the backend type during the build process and assign a container name for improved management during runtime.
=> Add interactive backend selection and container naming

starexec-proxy-provers/make_proxy.py
- Replaces the default archive creation with a subprocess call to the tar command using container-safe flags.
- Prevents permission and ownership issues in containerized environments.
- Implements error handling that falls back to the original method if the tar command fails.
- Improves logging for easier debugging and maintenance.
=> Fix container-safe tar archive creation

starexec-containerised/Dockerfile, starexec-containerised/init-starexec.sh
- **Restructure Build and Runtime Configuration:**  
- Organizes package installation, permission settings, and SSH configurations into logical sections.
- Adds system packages for SSH and ACL support to enhance container communication and access control.
- **Enhance Security & Reliability:**  
- Configures container-friendly ACLs and relaxed file modes for sandbox directories.
- Generates SSL certificates with proper file permissions.
- Applies idempotent SSH and Podman connection setups for both root and sandbox users.
- **Improve Maintainability:**  
- Separates build-time dependency installation from runtime permission adjustments.
- Provides clear logging and error handling to ease debugging.
Relates to internal container security and configuration improvements.
=> Improve Container Permissions & SSH/Podman Setup

provers-containerised/provers/iProver---3.9/Dockerfile
This PR fixes some issues related to opam in the Dockerfile of iProver
=> fix Dockerfile of iProver
